### PR TITLE
Web: custom cursor improvements

### PR DESCRIPTION
**Pull request by daxpedda**
This changes the custom cursor image generation on Web to use [`HTMLCanvasElement.toBlob()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) instead of `HTMLCanvasElement.toDataURL()`.

Unfortunately `toDataURL()` only generates a Base64 representation of the underlying image, this produces a lot of overhead. First during generation of the CSS value string, then when switching between them, because each time the `String` has to be sent through the FFI barrier.

`toBlob()` in comparison actually caches the image and produces a small data URL that is cheap to set and switch around. This is complicated though because `toBlob()` is callback based and not sync. So I had to implement some state machine that can do the right thing when the callback is triggered.
I had to store the previous pointer as well because just showing the default cursor until the loading of the cursor is done would cause some rapid blinking between cursors.

Additionally, now that we have the async machinery already in place, I moved to use `ImageBitmapRenderingContext` instead of `CanvasRenderingContext2D`, which should be more efficient as well.

Because of the async nature of all this, we have to take special care when fixing https://github.com/rust-windowing/winit/issues/3227 to not actually change the cursor if its currently hidden.

Note: encountered this bug on FF https://bugzilla.mozilla.org/show_bug.cgi?id=1336764.

---

If you are still working on something you don't have to merge this right now, I'm happy to rebase this after you are done.

### CODE REVIEW

**Comment by eero-lehtinen** [comment]
It's surprisingly complicated, but I guess that is what you get if you want to efficiently and correctly communicate with js.

And I don't think I will be touching the web stuff anymore so should I merge now?

**Comment by daxpedda** [comment]
Yeah unfortunately ... a whole state machine is required. It's like this for a lot of stuff in the Web backend in Winit, no way around that unfortunately unless we move whole Winit to async :rofl:.

Yeah, you can merge it if it's fine with you.

**Comment by daxpedda** [comment]
If there is any problem with Web just ping me, I can fix things with PRs like this.
But generally speaking Web is done now.

**Comment by daxpedda** [comment]
Rebased!

**Comment by eero-lehtinen** [comment]
Yeah sorry I made some squashes which broke the merge

**Comment by daxpedda** [comment]
All good!

**Comment by eero-lehtinen** [comment]
I noticed that these changes make the default cursor flash in and out pretty often when holding down `A` in the `custom_cursors` example in Chrome, doesn't happen in Firefox. I'm using x11 and have a 144hz screen, so maybe that affects something.

Also this Firefox bug makes animated cursors really annoying but I guess we can't do anything about it.

**Comment by eero-lehtinen** [comment]
Also seems to happen on windows but only when moving the cursor at the same time. And happens the same way on my 60hz monitor so that doesn't seem to matter.

**Pull request merged**
